language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy: packtracker-app
api_key:
secure: j4/2YueBIp86yVKkc6UCRbWGesE+XCemmRPddlwAIBwtS540zgrCZN5yOzvrf6k1tmwDW91fBbPu8kvuGNLGFJlZLPFWXOEOywSzTuGHcyrgt7X0P02llra42q0prKHEuMR6iOGnqbeHVkfXcpmnJU/SMcGT5mYy0buehTk2dLTprJbqqAoVbyqQ3uNWi5xv29hugaueEm4QqCbqoMTVASQycrdg8mlW9gZ6aNfWm5J0MV4fqXgZRlNFgE+8+VNBMi0LhoUgkkJRvbsRWWlaIF5QGXjTwmUx4QlYuLOsbzNWJ8vFVIWiEO5Y5ryYJVWOp/79FptgZpxyQYY7Z17QCcBXOiEfIWNYfP7QHf8SbSKkPfEs3sMulFUBuiywzZj/EHxBp6Ne9qjtkkCpTo9S3L4k51mE8JdZw9Q8hz8b5D9xYiXBfK9TyrI7NeKGCr0VhZewHuIuRt6pLpH4Iu3V6WEe6V7CCBWhOEA5DZNgtLy7KUl5CBdYCVhdtT8+9G75jO4xf8XKFQNQgXHKlCkG4I+4CXlxPlWE7wZbnZ98BdDXAVYejjHwRY8uDEQWqMu9pjm2Rx9fa6ugN+dIQmD0Xb41ebvM+zywqNEj6b6732Rb2JHAgFMuyv9q5Pb+UAa2Z7ZPoH5VNe9OsqFU0VHlHumGhYUIJWSosbZfGa5Yw8Y=
